// File generated by FlutterFire CLI.
// Contains Firebase configuration options for your app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configuration options for Firebase Web app
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrT5mpA6vLHeTKQcClk_xD4yA8GXCUO7s',
    appId: '1:307711515061:web:ec1d42ff947e71d06a21fc',
    messagingSenderId: '307711515061',
    projectId: 'cannasol-executive-dashboard',
    authDomain: 'cannasol-executive-dashboard.firebaseapp.com',
    storageBucket: 'cannasol-executive-dashboard.firebasestorage.app',
    measurementId: 'G-V49KE73S2R',
    databaseURL: 'https://cannasol-executive-dashboard-default-rtdb.firebaseio.com',
  );

  // Configuration options for Firebase Android app
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrT5mpA6vLHeTKQcClk_xD4yA8GXCUO7s',
    appId: '1:307711515061:web:ec1d42ff947e71d06a21fc',
    messagingSenderId: '307711515061',
    projectId: 'cannasol-executive-dashboard',
    storageBucket: 'cannasol-executive-dashboard.firebasestorage.app',
    databaseURL: 'https://cannasol-executive-dashboard-default-rtdb.firebaseio.com',
  );

  // Configuration options for Firebase iOS app
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrT5mpA6vLHeTKQcClk_xD4yA8GXCUO7s',
    appId: '1:307711515061:web:ec1d42ff947e71d06a21fc',
    messagingSenderId: '307711515061',
    projectId: 'cannasol-executive-dashboard',
    storageBucket: 'cannasol-executive-dashboard.firebasestorage.app',
    databaseURL: 'https://cannasol-executive-dashboard-default-rtdb.firebaseio.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  // Configuration options for Firebase macOS app
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrT5mpA6vLHeTKQcClk_xD4yA8GXCUO7s',
    appId: '1:307711515061:web:ec1d42ff947e71d06a21fc',
    messagingSenderId: '307711515061',
    projectId: 'cannasol-executive-dashboard',
    storageBucket: 'cannasol-executive-dashboard.firebasestorage.app',
    databaseURL: 'https://cannasol-executive-dashboard-default-rtdb.firebaseio.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );
  
  // Configuration options for Firebase Windows app
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrT5mpA6vLHeTKQcClk_xD4yA8GXCUO7s',
    appId: '1:307711515061:web:ec1d42ff947e71d06a21fc',
    messagingSenderId: '307711515061',
    projectId: 'cannasol-executive-dashboard',
    storageBucket: 'cannasol-executive-dashboard.firebasestorage.app',
    databaseURL: 'https://cannasol-executive-dashboard-default-rtdb.firebaseio.com',
  );
}
