# Makefile for Flutter Web Application

# Define the Flutter command
FLUTTER = flutter

# Target to build the Flutter web application
build:
	$(FLUTTER) build web

# Target to run the Flutter web application locally in Chrome
run-chrome:
	$(FLUTTER) run -d chrome

# Target to run the Flutter web application locally in Edge
run-edge:
	$(FLUTTER) run -d edge

# Target to run the Flutter web application locally in Safari
run-safari:
	$(FLUTTER) run -d safari

# Target to serve the Flutter web application in Chrome
serve-chrome:
	$(FLUTTER) serve -d chrome

# Target to serve the Flutter web application in Edge
serve-edge:
	$(FLUTTER) serve -d edge

# Target to serve the Flutter web application in Safari
serve-safari:
	$(FLUTTER) serve -d safari 